### ISSUE TITLE
Broken after update to HA 2022.4.0

### ISSUE THREAD

**Issue by Ultra9k** [shenxn/ha-dyson#119]
After the latest update to HA 2022.4.0, continuous monitoring, night mode and air quality target all stopped working.

Edit: and temperature also not working anymore

**Comment by Ultra9k** [comment]
I then updated the addon to your latest release (0.16.3) and now I get:

Error
This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant.

It's completely broken.

**Comment by rbnmk** [comment]
I have the same issue since updating to 2022.4.0 and updating to the latest HACS release. Now get this error in the logs on startup:

Setup failed for custom integration dyson_local: Unable to import component: cannot import name 'DysonPurifierHumidifyCoolFormaldehyde' from 'libdyson' (/usr/local/lib/python3.9/site-packages/libdyson/__init__.py)

**Comment by Linusten** [comment]
Same issue here... 

Unable to import component: cannot import name 'DysonPurifierHumidifyCoolFormaldehyde' from 'libdyson' (/usr/local/lib/python3.9/site-packages/libdyson/__init__.py)

**Comment by sultanhq** [comment]
as a temp fix, i used vscode (on my Home assitant) and removed all references (imports and or staments) to `DysonPurifierHumidifyCoolFormaldehyde` all back to working (for now until an update)

obviously that particular machine (DysonPurifierHumidifyCoolFormaldehyde) won't work though :-(

**Comment by BeHappy2021** [comment]
Thanks @sultanhq. This worked for me.

**Comment by Ultra9k** [comment]
> as a temp fix, i used vs-code (on my Home assistant) and removed all references (imports and or staments) to `DysonPurifierHumidifyCoolFormaldehyde` in an all files search.... now it's all back to working (for now until an update )`
> 
> obviously that particular machine (DysonPurifierHumidifyCoolFormaldehyde) won't work though :-(

Even the things that stopped working afte the latest HA update? (Continuous monitoring, temperature, etc?)

**Comment by BeHappy2021** [comment]
> Even the things that stopped working afte the latest HA update? (Continuous monitoring, temperature, etc?)

Yes. Only thing missing is air quality.

**Comment by Ultra9k** [comment]
Didn't work for me. I did that and then nothing worked anymore. I guess I'll have to wait for a fix to be released...

**Comment by fwump38** [comment]
I spent a long time trying to use this and libdyson to include the latest changes before they were released and I could never get it to work. I believe that [this](https://github.com/shenxn/ha-dyson/blob/main/custom_components/dyson_local/manifest.json#L9) part of `manifest.json` which pulls in the latest changes in libdyson isn't working properly

HACS does [support using a github tag or branch as the requirements](https://developers.home-assistant.io/docs/creating_integration_manifest/#requirements) but I think it's formatted incorrectly. Even when formatted correctly it still gives me the error that it can't import DysonPurifierHumidifyCoolFormaldehyde

Maybe @austinbeam can chime in as they were the one to add the support for that device and I think it was working for them.

I suspect that libdyson needs a new release pushed to pypi so the requirements for HACS can be input in the "normal" way and this issue might resolve itself...  cc: @kakise

Sadly, I'm waiting on DysonPurifierHumidifyCoolFormaldehyde because that's the device I have and I can't get this integration to work otherwise.

**Comment by austinbeam** [comment]
I think it needs the spaces, but it failed checks so I tried it without them (which also failed, but was merged). I *have* confirmed it is working with the spaces and it's been flawless for me.

Sorry for the trouble @fwump38 -- hope this helps.

https://github.com/shenxn/ha-dyson/commit/4e135cf4254c41a692a54e3a3485bf3c1bb654bd

**Comment by austinbeam** [comment]
I think we can all agree the best fix would be a new libdyson (@shenxn) release and restoring the manifest the way it was before to provide a new ha-dyson  release. Admittedly, my approach was a hack, but I did what I could to get my PH03 working. I tried to get the manifest changes to pass checks but they would not. I still believe https://github.com/shenxn/ha-dyson/commit/e742bae807758bc8a3d109ae30da602c5951ad01 has the right formatting although it did not pass checks because that's what I am using and it works. The temperature issue seems to be something else, at least for me.

Let me know how I can help folks, hate that it's causing trouble for anyone.

**Comment by BeHappy2021** [comment]
I'd like to thank you and the others putting the work in so that we have an integration that works at all with our devices. There's been a little glitch this time but these things happen.

**Comment by austinbeam** [comment]
As an interim fix for those dealing with issues and needing PH03/PH04 support, one option to consider is trying [my fork](https://github.com/austinbeam/ha-dyson).

I know this is not a long-term fix, but hopefully it might help someone if you just want to get it working. I went ahead and merged @Flameeyes outstanding pull request in this fork as well. Hopefully the main repo can get back in order soon. Everything is functional again for me. Good luck folks.

**Comment by Flameeyes** [comment]
> Sadly, I'm waiting on DysonPurifierHumidifyCoolFormaldehyde because that's the device I have and I can't get this integration to work otherwise.

https://github.com/shenxn/ha-dyson/issues/115#issuecomment-1090833923 should do the trick for that.

**Comment by Cully81** [comment]
Hi,

After the update to HA 2022.4.1 everything works fine for me again

**Comment by Anto79-ops** [comment]
My integration is now back to working after updating 2022.4.1!!

**Comment by Ultra9k** [comment]
Which integration version?? My 0.16.2 has the same problems with 2023.4.1. Is 0.16.3 working now?

**Comment by Anto79-ops** [comment]
Yes 0.16.3 now works on 2022.4.1 (for me at least).

**Comment by Ultra9k** [comment]
Not for me. Just tested it.

**Comment by atmezferix** [comment]
Yeah and mine, glad you sent the message I hadn't even noticed.

**Comment by c0bra99** [comment]
I updated Home Assistant to 2022.4.1 from 2022.3.7 today, saw all the unavailable dyson entities, then updated ha-dyson to 0.16.3 from 0.16.2. Now on startup I am getting this error in the log:

Setup failed for custom integration dyson_local: Unable to import component: cannot import name 'DysonPurifierHumidifyCoolFormaldehyde' from 'libdyson' (/usr/local/lib/python3.9/site-packages/libdyson/__init__.py)

I do not use a Formaldehyde sensing device, but it looks like the integration is not loading at all now, every entity is unavailable.

**Comment by Anto79-ops** [comment]
Perhaps I'll give a bit more information on my system.

I had 0.16.2 on 2022.3.7, working perfectly no problems, then I updated to 2022.4.0, this completely broke the Dyson integration doesn't even load giving the issue of the component Dyson formaldehyde can't import. 

There were some suggested fixes which I did not do or attempted to do so I just waited. 

This morning 2022.4.1 was available updated it then after restart, the Dyson integration was working perfectly including temperature reporting.

**Comment by c0bra99** [comment]
I have rolled ha-dyson back to 0.16.2 from 0.16.3 (on home assistant 2022.4.1). At least the useful temperature/humidity/on off switch entities are back working again, but now there are startup errors:

- Error adding entities for domain select with platform dyson_local
- Error while setting up dyson_local platform for select
- Error while setting up dyson_local platform for sensor
- Error while setting up dyson_local platform for switch
- Error while setting up dyson_local platform for binary_sensor

These startup errors do not seem to impact the important entities from working for me.. I'll leave mine on 0.16.2 for now.

**Comment by BeHappy2021** [comment]
All working fine for me on 2022.4.1 and 0.16.3. As I'd made edits to the source files I removed everything (first the devices, then the integration from HACS) restarted then added 0.16.3 and the devices again. Everything now appears to be working fine.

**Comment by Ultra9k** [comment]
Can't get it to work...

**Comment by Kakise** [comment]
Should work on v0.16.4 as mentioned in #115

**Comment by Ultra9k** [comment]
It doesn't though. Just updated.

**Comment by yosoyez** [comment]
Started working for me after the update as well

**Comment by c0bra99** [comment]
ha-dyson version 0.16.4-4 with home assistant 2022.4.1, all startup errors are gone and all entities are back to working!

Thank you!
