### ISSUE TITLE
Dyson Purifier Humidify+Cool Formaldehyde PH04

### ISSUE THREAD

**Issue by pelu89** [shenxn/ha-dyson#103]
Is there a way to support the Dyson Purifier Humidify+Cool Formaldehyde PH04. At the moment I cannot get it to connect via the Dyson integration. 

Greetings,

**Comment by GitPetri** [comment]
This is probably related to https://github.com/shenxn/ha-dyson/issues/86#issuecomment-1030789168 - the current libdyson version integrated to ha-dyson is too old to recognize the model (at least 358E). Still guessing that bumping libdyson to later release would solve the problem.

**Comment by Kakise** [comment]
v0.16.4 bumped libdyson and v0.16.4-3 added an experimental HCHO sensor, could you test it ?

**Comment by GitPetri** [comment]
Adding Dyson Cloud integration to HA fails.
Error pop-up text after ADD INTEGRATION -> Dyson Cloud:

`This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant.
`

And the corresponding home assistant log entries (libdyson set to debug):

`[homeassistant.util.package] Attemting install of libdyson==0.8.11
`

`[homeassistant.config_entries] Error occurred loading configuration flow for integration dyson_cloud: cannot import name 'DysonPurifierHumidityCoolFormaldehyde' from 'libdyson' (/usr/local/lib/python3.9/site-packages/libdyson/__init__.py)
`

There is only perl in /usr/local/lib, the python3.9 installation directory is /usr/lib but no libdyson under site-packages

Running libdyson get_devices.py (on another computer) returns proper Serial/Name/Device Type/Credential -entries for both my devices (358E and 520)

HA 2022.4.1 (HASS OS distribution)
Dyson Local in HACS v0.16.4-4
Dyson Cloud in HACS v0.14.0

Now even the attempt to install Dyson Local integration fails, ends up in same errors. The only difference being string `dyson_cloud` vs `dyson_local` in the log entry

**Comment by Kakise** [comment]
Seems like for some reason it doesn't install the proper libdyson version ? Can you try to delete manually Dyson_local and libdyson and then reinstall it ?

**Comment by GitPetri** [comment]
Will do

**Comment by GitPetri** [comment]
- logged out from Dyson phone app
- Dyson local and Dyson cloud removed from HACS integration screen
- Nothing libdyson visible with `cd /;sudo find . -name libdyson`
- restart Home Assistant
- install Ha Dyson Cloud via HACS (v0.14.0) [<- BAD IDEA, see below]
- install Ha Dyson via HACS (v0.16.4-4)
- dyson_cloud and dyson_local visible in config/custom_components
- restart Home Assistant
- Configuration -> Add integration -> Dyson Cloud: log shows `Attempting install of libdyson==0.8.6` [<- BAD IDEA, see below]
- and same errors as in previous post
- Dyson local and Dyson cloud removed from HACS integration screen
- install only Dyson Local via HACS
- restart Home Assistant
- Configuration -> Add integration -> Dyson Local: log shows `Attempting install of libdyson==0.8.11`
- Dyson Local config UI opens, -> 'setup manually'

Now I got my 358E and 520 devices configured.
So looks like Dyson Cloud in HACS still has linking to older libdyson and messes up the integration for Dyson Local too.

**Comment by GitPetri** [comment]
i.e. @Kakise Thank You so much!

**Comment by Anto79-ops** [comment]
@GitPetri may I ask, what machine is the 358E? 

At the moment, I have 2 Dyson Purifier Hot+Cool Formaldehyde (purifying fan heater) HP09 and I cannot add them. With the right credentials and password and the latest version that supports the machine (v0.16.4-4): when I press submit, I get failed to connect, and even after pressing it multiple times (> 20). However, when I change the machine type Dyson Pure Hot + Cool (New) during the setup process, it add to the integration on the first submit and the machine is added as a 527E in the integration....it works, but of course I have no formaldehyde information.

**Comment by lone-cloud** [comment]
Dyson Purifier Hot+Cool Formaldehyde "works" for me as of the latest patch. Works is in quotes because the setup process is all sorts of buggy. This machine has to be added through the cloud integration and then the integration must be disabled otherwise it will break the local dyson integration after the next ha restart with the same kinds of errors that @GitPetri posted above. After following those two steps, it's been working well for me.

**Comment by GitPetri** [comment]
> @GitPetri may I ask, what machine is the 358E?
> 
> At the moment, I have 2 Dyson Purifier Hot+Cool Formaldehyde (purifying fan heater) HP09 and I cannot add them. With the right credentials and password and the latest version that supports the machine (v0.16.4-4): when I press submit, I get failed to connect, and even after pressing it multiple times (> 20). However, when I change the machine type Dyson Pure Hot + Cool (New) during the setup process, it add to the integration on the first submit and the machine is added as a 527E in the integration....it works, but of course I have no formaldehyde information.

It's this one https://www.fi.dyson.com/tuuletin-tai-ilmankasittelylaite/purifer-humidifier/dyson-purifier-humidify-cool1/dyson-humidify-cool-valkoinen-hopea which is probably [PH3A ](https://www.dyson.com/air-treatment/air-purifier-humidifiers/purifier-humidify-cool-auto-react-ph3a)

**Comment by Punkerschaf** [comment]
Hey Guys,
I have the syme problems integrating my PH04.
Ha-dyson is installed manually, not via HACS on my system, so i got my credentials also manually cloning and executing get_credentials from libdyson (I hope, they are correct).

With this information i tried to configure Dyson Local (and also trief Cloud) as said in Readme. Got Error popup saing "not configurable via UI" and following Error in Log:
```
Logger: homeassistant.config_entries
Source: config_entries.py:784 
First occurred: 13:41:48 (4 occurrences) 
Last logged: 13:56:58

Error occurred loading configuration flow for integration dyson_cloud:
cannot import name DysonPurifierHumidifyCoolFormaldehyde'
from 'libdyson' (/usr/local/lib/python3.10/site-packages/libdyson/__init__.py)
```

As I understand, ha-dyson has not the latest version of libdyson. Is the a way to updating this manually without using HACS or compiling on my own? Or do I have to wait for this on ha-dyson?
Thanks for an answer.

Edit: HA Version is 2022.7.0, ha-dyson is 0.16.4-4

Edit No. 2: Works with HA Version 2022.7.1

**Comment by pelu89** [comment]
Works for me!
Am 8. Apr. 2022, 20:38 +0200 schrieb Kakise ***@***.***>:
