### ISSUE TITLE
Integration not working after updating HA to 2025.1+

### ISSUE THREAD

**Issue by DanielTerletzkiy** [shenxn/ha-dyson#204]
after now being on HA v2025.2 for a few days, I noticed, that my Dyson was unreachable and i found this in the logs
```
ImportError: cannot import name 'SUPPORT_DIRECTION' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/__init__.py)
2025-02-05 21:42:22.093 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration dyson_local with title: Pure Humidify+Cool and entry_id: 686e45891d07f9380a3b9f3af4eed112, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1, please report this issue
Stack (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 707, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 678, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2033, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2347, in async_forward_entry_setup
    _report_non_awaited_platform_forwards(entry, "async_forward_entry_setup")
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1193, in _report_non_awaited_platform_forwards
    report_usage(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 234, in report_usage
    _LOGGER.warning(msg, stack_info=True)
```

also also

```
2025-02-05 21:42:16.180 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'dyson_local' calls async_forward_entry_setup for integration, dyson_local with title: Pure Humidify+Cool and entry_id: 686e45891d07f9380a3b9f3af4eed112, which is deprecated, await async_forward_entry_setups instead at custom_components/dyson_local/__init__.py, line 85: hass.async_create_task(. This will stop working in Home Assistant 2025.6, please create a bug report at https://github.com/shenxn/ha-dyson/issues
```

**Comment by DanielTerletzkiy** [comment]
https://github.com/shenxn/ha-dyson/issues/185
